ALTER TABLE listings
  ADD COLUMN IF NOT EXISTS condition               text,
  ADD COLUMN IF NOT EXISTS stock                   integer,
  ADD COLUMN IF NOT EXISTS free_shipping           boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS expires_at              timestamptz,
  ADD COLUMN IF NOT EXISTS view_count              integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sale_type               text DEFAULT 'direct',
  ADD COLUMN IF NOT EXISTS is_featured             boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS featured_fee            numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS weight_kg               numeric(8,3),
  ADD COLUMN IF NOT EXISTS length_cm               numeric(8,2),
  ADD COLUMN IF NOT EXISTS width_cm                numeric(8,2),
  ADD COLUMN IF NOT EXISTS height_cm               numeric(8,2),
  ADD COLUMN IF NOT EXISTS shipping_by_seller      boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS shipping_price          numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shipping_subsidy        numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS allow_personal_delivery boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS auction_start_at        timestamptz,
  ADD COLUMN IF NOT EXISTS auction_end_at          timestamptz,
  ADD COLUMN IF NOT EXISTS auction_starting_bid    numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auction_bid_increment   numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auction_highest_bid     numeric(10,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS color_variants          text[],
  ADD COLUMN IF NOT EXISTS size_variants           text[],
  ADD COLUMN IF NOT EXISTS tags                    text[],
  ADD COLUMN IF NOT EXISTS attributes              jsonb,
  ADD COLUMN IF NOT EXISTS subcategory             text,
  ADD COLUMN IF NOT EXISTS wholesale_tiers         jsonb,
  ADD COLUMN IF NOT EXISTS product_type            text DEFAULT 'physical',
  ADD COLUMN IF NOT EXISTS digital_delivery_type   text,
  ADD COLUMN IF NOT EXISTS digital_delivery_fields jsonb,
  ADD COLUMN IF NOT EXISTS description_blocks      jsonb,
  ADD COLUMN IF NOT EXISTS description_blocks_meta jsonb,
  ADD COLUMN IF NOT EXISTS size_stock              jsonb,
  ADD COLUMN IF NOT EXISTS size_type               text;
